In [217]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import numpy as np
np.random.seed(10)

In [218]:
X,y=load_breast_cancer(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)

In [3]:
X_train.shape

(426, 30)

In [172]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [212]:

weights1=np.random.random((inp.shape[1],2))
bias1=0
weights2=np.random.random((2,2))
bias2=0
weights3=np.random.random((2,1))
bias3=0
inp=np.random.random((5,3)) #dummy data
def forward(weights1,bias1,weights2,bias2,weights3,bias3,data):
    input_layer=sigmoid(np.dot(data,weights1)+bias1)
    hidden_layer=sigmoid(np.dot(input_layer,weights2)+bias2)
    output=np.dot(hidden_layer,weights3)+bias3
    return output

In [214]:
forward(weights1,bias1,weights2,bias2,weights3,bias3,inp)

array([[0.68455424],
       [0.67524161],
       [0.70665586],
       [0.70238912],
       [0.71791931]])

In [186]:
np.weights3.shape

(2, 1)

In [146]:
inp[0].shape

(3,)

In [147]:
inp[0]

array([0.06143108, 0.59817351, 0.88592025])

In [149]:
np.dot(inp,weights1)

array([[0.3026453 ],
       [0.03948626],
       [0.27738455],
       [0.3127543 ],
       [0.2949261 ]])

In [150]:
inp

array([[0.06143108, 0.59817351, 0.88592025],
       [0.41213378, 0.0382722 , 0.0808424 ],
       [0.08191454, 0.80936733, 0.800694  ],
       [0.01690981, 0.86129433, 0.91130022],
       [0.40087668, 0.2868907 , 0.84304489]])