In [1]:
import tensorflow as tf


In [2]:
tf.compat.v1.disable_eager_execution() #disable version 2 

In [4]:
X=tf.constant("Tensorflow")
X

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [5]:
sess=tf.compat.v1.Session()
s=sess.run(X)
print(s)
sess.close()

b'Tensorflow'


In [6]:
x=tf.constant(4)
y=tf.constant(8)

z=tf.add(x,y)
z

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [7]:
with tf.compat.v1.Session() as sess:
    res=sess.run(z)
    print(res)

12


In [8]:
import numpy as np 
var1=np.arange(1,13,dtype=np.int32)
var2=np.arange(15,27,dtype=np.int32)

In [9]:
mat1=tf.constant(var1,shape=[3,4])
mat2=tf.constant(var2,shape=[4,3])

c=tf.matmul(mat1,mat2)
c

<tf.Tensor 'MatMul:0' shape=(3, 3) dtype=int32>

In [10]:
with tf.compat.v1.Session() as sess:
    print(sess.run(c))

[[210 220 230]
 [522 548 574]
 [834 876 918]]


In [11]:
v1=tf.constant([1,2,3,4])
v2=tf.constant([6,7,8,9])

s=tf.add(v1,v2)
sb=tf.subtract(v1,v2)
m=tf.multiply(v1,v2)
d=tf.divide(v1,v2)

with tf.compat.v1.Session() as sess:
    print(sess.run(s))
    print(sess.run(sb))
    print(sess.run(m))
    print(sess.run(d))

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


In [22]:
#h=wx+b
w=tf.Variable([[1,2,3]],shape=(1,3))
w
X=tf.constant([[3],[4],[4]],shape=(3,1))
b=tf.Variable(1)
h=tf.add(tf.matmul(w,X),b)
h

<tf.Tensor 'Add_2:0' shape=(1, 1) dtype=int32>

In [24]:
init=tf.compat.v1.global_variables_initializer()

In [25]:
with tf.compat.v1.Session() as sess:
    sess.run(init)
    print(sess.run(h))

[[24]]
